name: "Release Github"

on:
  push:
    tags:
      - "v*"
jobs:
  build_test:
    name: "Build & Testing"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        run: |
          sudo apt-get install cmake

      - name: Build & Testing
        run: |
          make build_type=Debug
          make run-tests
  
  build_documentation:
    name: "Build documentation"
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install gsfonts-other
          sudo apt-get install doxygen
          chmod 777 ./scripts/docs.sh
      - name: Run docs script
        run: |
          ./scripts/docs.sh
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
