name: Gauss build and test

on: push

jobs:
  cmake:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: install cmake
      run: sudo apt-get install cmake

  binaries:
    runs-on: ubuntu-latest
    environment: deploy
    needs: cmake
    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: gaussbinaries
        path: build/

  tests:
    runs-on: ubuntu-latest
    environment: deploy
    needs: binaries
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: gaussbinaries
        path: build/
    - name: run tests
      run: sudo make run-tests

