name: Gauss build and test

on: push

jobs:
  cmake:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: install cmake
      run: sudo apt-get install cmake
    - name: configure project environment
      run: make environment
    - name: build project binaries
      run: make binaries
    - name: run tests
      run: make run-tests

