name: Gauss build and test

on: push

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: install cmake
      run: sudo apt-get install cmake

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - name: build project
      run: make build-conf && cd build && make

  tests:
    needs: build
    - name: run ctest
      run: cd build && ctest

