name: Gauss build and test

on: push

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
    - name: install cmake
      run: sudo apt-get install cmake

  build:
    runs-on: ubuntu-latest
    needs: cmake
    steps:
    - name: build project
      run: make build-conf && cd build && make

  ctest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: run ctest
      run: cd build && ctest

