name: NPM publish

on:
  push:
    branches:
    - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: sudo apt-get install cmake
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
    - name: Build WASM and JS bindings
      run: make emsdk_path=./emsdk release-wasm-js
    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          const dash_index = no_v.lastIndexOf('-')
          const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
          core.setOutput('tag', tag)
          core.setOutput('no-v', no_v)
          core.setOutput('no-dash', no_dash)
    - name: Write version
      run: sed -i 's/PACKAGE_VERSION/${{ steps.set_version.outputs.no-dash }}/g' releases/wasm-js/package.json
    - uses: actions/upload-artifact@master
      with:
        name: wasm-js
        path: releases/wasm-js/

  publish:
    runs-on: ubuntu-latest
    environment: deploy
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: wasm-js
          path: gaussjs/

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Remove unnecessary files
        working-directory: gaussjs
        run: rm index.cpp

      - name: Run npm ci
        working-directory: gaussjs
        run: npm ci

      - name: Publish package
        working-directory: gaussjs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
