name: Run Tests

on:
  push:
    tags:
      - "v*"
jobs:
  cmake:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
    - name: install cmake
      run: sudo apt-get install cmake

  build_and_test:
    runs-on: ubuntu-latest
    environment: deploy
    needs: cmake
    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: make
    - name: run tests
      run: make run-tests

