name: Windows Build & Testing

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          choco install cmake make
          cmake --version

      - name: Configure
        run: |
          cmake .

      - name: Build
        run: |
          cmake --build .

      # - name: Configure Environment
      #   run: |
      #     make build_type=Debug environment
      # - name: Build
      #   run: |
      #     make build_type=Debug binaries
      # - name: Testing
      #   run: |
      #     make run-tests
